### PR TITLE
Escape file paths before using them in URL path

### PR DESCRIPTION
**Pull request by bcomnes**
Closes https://github.com/netlify/open-api/issues/113

### CODE REVIEW

**Comment by bcomnes** [comment]
Still WIP because I'm not 100% sure this fixes the issue yet.

**Comment by bcomnes** [comment]
Might need http://golang.org/pkg/net/url/#PathEscape instead.  I'll investigate tomorrow.

**Comment by fool** [comment]
cc @rybit could you spend 20 minutes today reviewing / attempting to fix up if needed?

**Comment by bcomnes** [comment]
This is purely an idea based on an issue I ran into with the JS client, I never got a chance to experiment if this works or not.

**Comment by bcomnes** [comment]
We haven't seen this in ages, so closing for now.

**Pull request closed without merging**
