### PR TITLE
Regenerate go client

### PR DESCRIPTION
**Pull request by Mongey**
So that #164 can be used

### CODE REVIEW

**Comment by peckeltw** [comment]
@Mongey thanks a lot! Hopefully this can be merged soon :-)

**Comment by peckeltw** [comment]
Any update on this PR? It would help a lot ... Thanks

**Comment by mraerino** [comment]
We are so sorry, that this has not been addressed yet. We will try to get it out asap.

**Comment by ehmicky** [comment]
@peckeltw I believe this is solved now. Please let us know if this works!

**Comment by TotempaaltJ** [comment]
Hey @ehmicky, is this released?

**Comment by ehmicky** [comment]
I am a Go programmer, but my understanding is that Go would just import GitHub files as is, i.e. no release is needed? @mraerino could you please confirm?

**Comment by TotempaaltJ** [comment]
Not a Go dev, but I'm pretty sure that isn't actually the case. Tagged releases still exist in Go as far as I can tell.

**Comment by maartenvanvliet** [comment]
Yes, a release is needed for https://github.com/terraform-providers/terraform-provider-netlify/issues/32 to be resolved properly. 

It could depend on a git commit in the go.mod file but that's a bit of a hack.

**Comment by ehmicky** [comment]
@mraerino What do you think?

**Comment by mraerino** [comment]
yeah, we should release. I'm going to take care of it

**Comment by mraerino** [comment]
Finally released :tada:
https://github.com/netlify/open-api/releases/tag/v0.12.0

**Pull request closed without merging**
