### PR TITLE
New js strategey

### PR DESCRIPTION
**Pull request by bcomnes**
This is an improved open-api strategy for JS:

- Creates a module that ships just the spec file, clients can consume this directly or use something like https://github.com/swagger-api/swagger-js which is a dynamic client creator.
- Update the website to use the latest swagger ui
- Also expose the yml spec on the website.

### CODE REVIEW

**Comment by bcomnes** [comment]
I'll need to update the user PR as well, but I still haven't successfully been able to rebuild the go libs, so maybe @futuregerald and I can figure that out soon.

**Comment by bcomnes** [comment]
I think maybe the deploy notifications are busted after the team move.  Here is the deploy preview:

https://new-js-strategey--open-api.netlify.com/?_ga=2.6108278.479227081.1532541756-1726230660.1514319085

**Comment by futuregerald** [comment]
Let's set something up for Monday or Tuesday next week so we can resolve the issue with generating Go bindings on your machine. Otherwise, this LGTM.

**Comment by calavera** [comment]
@bcomnes can you post more information about your problems building the Go bindings?

**Comment by bcomnes** [comment]
Here is the log output:
https://gist.github.com/bcomnes/637de1facd678ad9e32c62a5a4726997

```console
$ make test
cd ./go && go test -v $(go list ./... | grep -v /vendor/)
# github.com/netlify/open-api/go/porcelain/http
porcelain/http/http_test.go:15:2: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/stretchr/testify/require (from $GOROOT)
	/Users/bret/go/src/github.com/stretchr/testify/require (from $GOPATH)
FAIL	github.com/netlify/open-api/go/porcelain/http [setup failed]
# github.com/netlify/open-api/go/models
models/account_membership_capabilities.go:17:6: AccountMembershipCapabilities redeclared in this block
	previous declaration at models/account_membership.go:184:6
models/account_membership_capabilities.go:27:6: (*AccountMembershipCapabilities).Validate redeclared in this block
	previous declaration at models/account_membership.go:198:6
models/account_membership_capabilities.go:46:6: (*AccountMembershipCapabilities).validateCollaborators redeclared in this block
	previous declaration at models/account_membership.go:217:6
models/account_membership_capabilities.go:66:6: (*AccountMembershipCapabilities).validateSites redeclared in this block
	previous declaration at models/account_membership.go:236:6
models/account_membership_capabilities.go:87:6: (*AccountMembershipCapabilities).MarshalBinary redeclared in this block
	previous declaration at models/account_membership.go:256:6
models/audit_log_payload.go:19:6: AuditLogPayload redeclared in this block
	previous declaration at models/audit_log.go:93:6
models/payment_method_data.go:17:6: PaymentMethodData redeclared in this block
	previous declaration at models/payment_method.go:111:6
models/site_processing_settings.go:17:6: SiteProcessingSettings redeclared in this block
	previous declaration at models/site.go:278:6
models/site_processing_settings_html.go:17:6: SiteProcessingSettingsHTML redeclared in this block
	previous declaration at models/site.go:433:6
models/site_processing_settings_images.go:17:6: SiteProcessingSettingsImages redeclared in this block
	previous declaration at models/site.go:472:6
models/account_membership_capabilities.go:87:6: too many errors
make: *** [test] Error 2
```

**Comment by bcomnes** [comment]
Looks like I was missing a dep.  Here is the output with it installed:

```
$ make test
cd ./go && go test -v $(go list ./... | grep -v /vendor/)
# github.com/netlify/open-api/go/models
models/account_membership_capabilities.go:17:6: AccountMembershipCapabilities redeclared in this block
	previous declaration at models/account_membership.go:184:6
models/account_membership_capabilities.go:27:6: (*AccountMembershipCapabilities).Validate redeclared in this block
	previous declaration at models/account_membership.go:198:6
models/account_membership_capabilities.go:46:6: (*AccountMembershipCapabilities).validateCollaborators redeclared in this block
	previous declaration at models/account_membership.go:217:6
models/account_membership_capabilities.go:66:6: (*AccountMembershipCapabilities).validateSites redeclared in this block
	previous declaration at models/account_membership.go:236:6
models/account_membership_capabilities.go:87:6: (*AccountMembershipCapabilities).MarshalBinary redeclared in this block
	previous declaration at models/account_membership.go:256:6
models/audit_log_payload.go:19:6: AuditLogPayload redeclared in this block
	previous declaration at models/audit_log.go:93:6
models/payment_method_data.go:17:6: PaymentMethodData redeclared in this block
	previous declaration at models/payment_method.go:111:6
models/site_processing_settings.go:17:6: SiteProcessingSettings redeclared in this block
	previous declaration at models/site.go:278:6
models/site_processing_settings_html.go:17:6: SiteProcessingSettingsHTML redeclared in this block
	previous declaration at models/site.go:433:6
models/site_processing_settings_images.go:17:6: SiteProcessingSettingsImages redeclared in this block
	previous declaration at models/site.go:472:6
models/account_membership_capabilities.go:87:6: too many errors
=== RUN   TestRetryableTransport
--- PASS: TestRetryableTransport (0.41s)
=== RUN   TestRetryableTransportExceedsMaxAttempts
--- PASS: TestRetryableTransportExceedsMaxAttempts (1.00s)
=== RUN   TestRetryableWithDifferentError
--- PASS: TestRetryableWithDifferentError (0.00s)
=== RUN   TestRetryableTransport_POST
--- FAIL: TestRetryableTransport_POST (0.00s)
	require.go:794: 
			Error Trace:	http_test.go:177
			Error:      	Received unexpected error:
			            	Post http://127.0.0.1:53214/: http: ContentLength=14 with Body length 28
			Test:       	TestRetryableTransport_POST
FAIL
FAIL	github.com/netlify/open-api/go/porcelain/http	1.448s
make: *** [test] Error 2
```

**Comment by bcomnes** [comment]
I can dig more into it Monday, but let me know if any ideas jump out at you.

**Comment by bcomnes** [comment]
After talking with @calavera about this one, we can merge this since its independent of the go libs.  We should get those regenerating soon though.

**Pull request merged**
