### PR TITLE
chore: update logo in docs

### PR DESCRIPTION
**Pull request by jasonbarry**
Before: 
CleanShot 2023-03-07 at 09 10 53@2x

After: 
CleanShot 2023-03-07 at 09 10 30@2x

### CODE REVIEW

**Review by ryanbonial — APPROVED** [review]

**Review by sean-roberts — DISMISSED** [review]
didn't check if the ratios matter to where it's being used in the site

**Review by kaelig — DISMISSED** [review]

**Comment by kaelig** [comment]
Looking good in the DP!

**Comment by jasonbarry** [comment]
Just noticed I didn't update the logo in the readme, hold plz

**Comment by jasonbarry** [comment]
OK now ready to go :-)

**Review by kaelig — APPROVED** [review]

**Pull request merged**
