### PR TITLE
docs: update dependency redoc-cli

### PR DESCRIPTION
**Pull request by jasonbarry**
This PR updates the [redoc-cli](https://www.npmjs.com/package/redoc-cli) dependency to upgrade the look and feel of our API reference docs. It also sorts the operation in the sidebar alphabetically, closing #388. 

## Test plan

1. Navigate to the [Deploy Preview](https://deploy-preview-390--open-api.netlify.app/) and ensure nothing seems buggy or out of place
2. Ensure that clicking on an operation in the sidebar adds a hash to the URL, and refreshing the page takes you to the same anchor

### CODE REVIEW

**Comment by jasonbarry** [comment]
Not liking this in the footer, I wonder if it can be removed

Screenshot 2022-07-28 at 11 19 26

**Comment by jasonbarry** [comment]
Looks like we have [consensus](https://netlify.slack.com/archives/C6NVA4FS6/p1659033753748529?thread_ts=1659032754.192899&cid=C6NVA4FS6) to go forward -- tagging @jackbrewer and @pvorozhe for 👀

**Review by pvorozhe — APPROVED** [review]
LGTM, not seeing anything off.

Out of curiosity, why do we not use renovate with stable versions for this?

**Comment by jasonbarry** [comment]
@pvorozhe good Q! I'm not sure. I see [some PRs from Dependabot](https://github.com/netlify/open-api/pulls/app%2Fdependabot), but idk why this repo isn't configured with Renovate like our others.

**Pull request merged**
