### PR TITLE
Add prerender property to site

### PR DESCRIPTION
**Pull request by cstaud**
Solves #279

### CODE REVIEW

**Review by FawazFarid — APPROVED** [review]
LGTM 👍🏼

**Review by rstavchansky — APPROVED** [review]
I always feel silly reviewing the docs for these very minimal API docs, but I see the new property in the output. 👍🏻

**Comment by rstavchansky** [comment]
Looks like you're missing a label

**Comment by cstaud** [comment]
so maybe someone with write access could merge this?

**Comment by cstaud** [comment]
triggering a release would be also nice afterwards ;-)

**Comment by cstaud** [comment]
@FawazFarid @rstavchansky can we go on here?

**Comment by FawazFarid** [comment]
On it

**Pull request merged**
