### PR TITLE
Remove listForms endpoint

### PR DESCRIPTION
**Pull request by FawazFarid**
This PR removes the deperecated listForms API endpoint from swagger.yml and regenerates the Go client.

### Relevant links
https://github.com/netlify/bitballoon/issues/7814

### CODE REVIEW

**Review by rstavchansky — APPROVED** [review]
The output of the OpenAPI updates looks fine, but it looks like this issue needs a label and that a couple of other tests may not be passing. I'm approving for the docs side.

**Comment by keiko713** [comment]
happy to double check once it's out of draft, but so far looking good 🎉

**Comment by FawazFarid** [comment]
@keiko713 thanks for looking into this, just made some extra changes. I think it's ready for review

**Review by vbrown608 — APPROVED** [review]
Looks good to me!

**Review by keiko713 — APPROVED** [review]
looks good to me too 🎉

**Pull request merged**
