### PR TITLE
Add forms functions to porcelain

### PR DESCRIPTION
**Pull request by lannonbr**
I added functions in the porcelain package to be able to list forms as well as list form submissions. This is a prerequisite to add functionality to list these inside netlifyctl.

### CODE REVIEW

**Comment by calavera** [comment]
awesome! Thanks so much!

**Comment by calavera** [comment]
I'm looking at the spec and I'm not sure if this is exactly correct. In this current configuration, listForms will list all forms for sites that belong to your authenticated user. You probably want only forms for a specific site. In order to get forms only for a specific site, we need to pass the "site_id" parameter in the query.

Do you mind adding that parameter to the swagger spec?
It should go here: https://github.com/netlify/open-api/blob/master/swagger.yml#L847
You can copy the parameter definition from this other endpoint, but removing `required: true`: https://github.com/netlify/open-api/blob/master/swagger.yml#L876

**Comment by lannonbr** [comment]
Well, I currently am thinking of having it when I run `$ netlifyctl forms` to list a table of all forms with a few fields such as the form id and name, the site id/name, and the number of submissions to the form. I could create a ListFormsBySiteId function after implementing that site_id param as well so then a user could run `$ netlifyctl forms --site-id <site_id>" and get just the forms for a particular site. What would you recommend?

**Comment by lannonbr** [comment]
There actually was a duplicate endpoint for /sites/{site_id}/deploys/{deploy_id} so I removed one of them. As well, I just added both the parameter and a ListFormsBySiteId function. after a few failing tests, everything should work now on the API side

**Comment by lannonbr** [comment]
I found there is an endpoint of /sites/{site_id}/forms to get a site's forms which is in the spec here: https://github.com/netlify/open-api/blob/master/swagger.yml#L147. Should I revert the changes and use that endpoint, or just leave my code as is @calavera?

**Comment by lannonbr** [comment]
@calavera any progress looking over this?

**Comment by calavera** [comment]
LGTM

**Pull request merged**
